### ISSUE TITLE
Make "known" values implicit when a value is changed to anything other than "none"

### ISSUE THREAD

**Issue by beckydvn** [dialogue-planning/plan4dial#15]
When explicitly defining an action, the `known` value has to be stated explicitly when a value is updated. Take this example from plan4dial's `bank_bot`:

```
  offer-new:
    type: dialogue
    message_variants:
      - Would you like to create a new account?
      - I can also create a new account for you. Would you like to do that today?
    condition:
      tried-create:
        value: false
      task:
        known: false
    effect:
      start-task:
        oneof:
          outcomes:
            want-create:
              updates:
                task:
                  known: true
                  value: create account
              intent: confirm
```

It's a small change, but it would be less mental overhead for the user if the system could infer that `known` be set to true when the `value` is updated to something other than `none`.
